project 'CoreLocationARKit.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoreLocationARKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoreLocationARKit
  pod 'ARCL'
  
  target 'CoreLocationARKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoreLocationARKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
